# Generated by Django 4.1.5 on 2023-01-09 11:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllShayari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Mix', 'Mix'), ('Love', 'Love'), ('Dosti', 'Dosti'), ('Wish', 'Wish'), ('Sad', 'Sad'), ('Dhokha', 'Dhokha'), ('Alone', 'Alone'), ('BreakUp', 'BreakUp'), ('Bhakti', 'Bhakti'), ('Deshbhakti', 'Deshbhakti'), ('Thought', 'Thought')], max_length=25)),
                ('tag', models.CharField(max_length=45)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=25)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
